### ISSUE TITLE
zerolog adaptor produces two `time` fields in JSON output

### ISSUE THREAD

**Issue by josephschorr** [jackc/pgx-zerolog#4]
Reference: https://github.com/authzed/spicedb/issues/58

When using the zerolog adapter with pgx, the produced logs have two `time` fields in JSON format. Example:

```
{"level":"debug","module":"pgx","args":["something"],"commandTag":"SELECT 1","pid":125,"sql":"SELECT foo FROM bar WHERE baz = $1","time":1.388792,"time":"2023-04-05T15:10:42-04:00","message":"Query"}
```

zerolog provides a means to change the `time` field value (https://github.com/rs/zerolog/blob/1f50797d7d24e4cf3a6407203bd694f3d35de724/event.go#L643), but that workaround suffers from breaking code that expects logs to have `time` as the timestamp of the log itself.

Would you accept a change to allow for renaming of the `time` field from `pgx`, perhaps to `duration`?

**Comment by jackc** [comment]
I think the subdictionary feature added in https://github.com/jackc/pgx-zerolog/commit/092863fdc57d6ea6bbe786f16001300da2415219 might solve the problem.

**Comment by josephschorr** [comment]
@jackc Awesome, will use that
